In [1]:
import numpy as np

In [2]:
n = 3
X = np.array([[1,1],[1,2],[2,3]])
print(X)
y = np.array([[1.5, 2, 3]])
w = np.array([[2, 2]])

[[1 1]
 [1 2]
 [2 3]]


In [3]:
X.shape

(3, 2)

In [4]:
y.shape

(1, 3)

In [5]:
w.shape

(1, 2)

In [6]:
A = y - w@X.T
A

array([[-2.5, -4. , -7. ]])

In [7]:
w@X.T

array([[ 4,  6, 10]])

In [8]:
np.dot(w,X.T)

array([[ 4,  6, 10]])

In [9]:
A.shape

(1, 3)

In [10]:
B = (y - w@X.T).T*X
B

array([[ -2.5,  -2.5],
       [ -4. ,  -8. ],
       [-14. , -21. ]])

In [11]:
B.shape

(3, 2)

In [12]:
np.array([[1, 2, 3]]).T*np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [13]:
S = np.sum( (y - w@X.T).T*X, axis=0, keepdims=True )
S

array([[-20.5, -31.5]])

In [14]:
S.shape

(1, 2)

In [15]:
S2 = np.sum( (y - w@X.T).T*X, axis=1, keepdims=True )
S2

array([[ -5.],
       [-12.],
       [-35.]])

In [16]:
S2.shape

(3, 1)

In [17]:
S3 = np.sum( (y - w@X.T).T*X, axis=0, keepdims=False )
S3

array([-20.5, -31.5])

In [18]:
S3.shape

(2,)

In [19]:
S4 = np.sum( (y - w@X.T).T*X, axis=1, keepdims=False )
S4

array([ -5., -12., -35.])

In [20]:
S4.shape

(3,)

In [21]:
kappa = 0.1
E = (1/(2*n)) *(np.sum((y-w@X.T)**2))
print("E = ", E)

w = w + kappa*((1/n)*(np.sum( (y - w@X.T).T*X, axis=0, keepdims=True )))
print("new w = ", w)

E = (1/(2*n)) *(np.sum((y-w@X.T)**2))
print("new E = ", E)

E =  11.875
new w =  [[1.31666667 0.95      ]]
new E =  1.3724999999999992
