# Notebook for testing the NumPy library:
**Author:** Andreas P. Koenzen

In [3]:
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Array Slicing and Reshaping

### newaxis
Adds another dimension to some array. 1D => 2D, 2D => 3D, etc.

In [7]:
a = np.arange(1, 4)
a

# this is the same as add one dimension as rows 
# of the same length as columns in a or no columns 
# for a.
a = a[:, np.newaxis]
a

# the property newaxis is just a None object, so we 
# can pass None as a subscript to our array.
type(np.newaxis)

array([1, 2, 3])

array([[1],
       [2],
       [3]])

NoneType

### All zeros 2D array:

In [6]:
np.zeros((10, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])