# Notebook for testing the NumPy library:
**Author:** Andreas P. Koenzen

In [2]:
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Array Slicing and Reshaping

### Reshape function

In [3]:
a = np.arange(1, 21)
np.reshape(a, (-1, 2, 2)) # In this case -1 equals an UNKNOWN DIMENSION, which means that it will infer that the necessary value is *5*.

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

### newaxis
Adds another dimension to some array. 1D => 2D, 2D => 3D, etc.

In [4]:
a = np.arange(1, 4)
a
a.shape

# this is the same as add one dimension as rows 
# of the same length as columns in a or no columns 
# for a.
a = a[np.newaxis, :]
a
a.shape

# the property newaxis is just a None object, so we 
# can pass None as a subscript to our array.
type(np.newaxis)

array([1, 2, 3])

(3,)

array([[1, 2, 3]])

(1, 3)

NoneType

### Shapes

![3D Array](https://cdncontribute.geeksforgeeks.org/wp-content/uploads/3D-array.jpg)

In [5]:
np.zeros((3, 4, 5)) # This means 3 arrays of 4 rows and 5 columns. In this case
                    # the first index is the depth or # of arrays.

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

### General Slicing

In [6]:
# All elements except the last. The same as arr[0:-1:1]
arr = np.arange(1, 10).reshape((3, 3))
arr
arr[:, 0:2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2],
       [4, 5],
       [7, 8]])

## Referencing / Indexing

In [7]:
# TODO: Implement using a Matrix as a subscript.

In [15]:
# Last element.
arr = np.arange(1, 11)
arr

arr[-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

10

In [16]:
# General:
arr = np.arange(1, 11)
arr

arr[-2:] # returns the 2 last elements as array elements, NOT as scalars! "See colon at the end".

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 9, 10])

In [28]:
# Element access in a 3D array.
# 3D array = Depth, Rows, Columns
arr = np.random.random((3, 32, 32))
arr

arr.shape[1:]

array([[[0.94391433, 0.58801962, 0.81721957, ..., 0.93888646,
         0.02994794, 0.59267003],
        [0.37464437, 0.57823463, 0.04101374, ..., 0.75804052,
         0.37758275, 0.38889388],
        [0.49657446, 0.43742256, 0.58838159, ..., 0.08868189,
         0.27151341, 0.08210867],
        ...,
        [0.99854983, 0.5268921 , 0.83947808, ..., 0.84350112,
         0.92979956, 0.45589897],
        [0.7980296 , 0.13261052, 0.04263041, ..., 0.63037254,
         0.81862111, 0.17929328],
        [0.14368469, 0.06936903, 0.29741151, ..., 0.97296993,
         0.30247203, 0.40547464]],

       [[0.65590061, 0.54274418, 0.91559164, ..., 0.20884171,
         0.7337434 , 0.6184312 ],
        [0.23478035, 0.36533527, 0.90251135, ..., 0.45493893,
         0.47480185, 0.92491891],
        [0.16651373, 0.60826128, 0.6789083 , ..., 0.06103033,
         0.71052859, 0.23383429],
        ...,
        [0.62974537, 0.0167975 , 0.48634128, ..., 0.0512628 ,
         0.12630745, 0.80130078],
        [0.1

(32, 32)

In [18]:
# Size along a given axis.
arr = np.random.random((32, 32, 3))
np.size(arr, axis=2)

3

In [10]:
# For loops.
arr = np.random.random((3, 4, 5)) # 3D array = Depth, Rows, Columns
arr
for i in range(0, np.size(arr, axis=0)): # Get the depth. Iterates through the depth.
    arr[i] # New array with one less dimension than the original.
    
    # Example: Get the element in the 2 row and 3 column of each depth/level.
    arr[i][1][2]

array([[[0.24800023, 0.33695557, 0.03353062, 0.58066617, 0.56607221],
        [0.17514119, 0.98660121, 0.4662178 , 0.81134032, 0.22050955],
        [0.71610125, 0.56825938, 0.51970461, 0.13970381, 0.29865019],
        [0.84912277, 0.42845382, 0.22731047, 0.23505944, 0.0809489 ]],

       [[0.2518992 , 0.32564831, 0.02008145, 0.23930571, 0.78363088],
        [0.32248647, 0.74212245, 0.43295834, 0.43518467, 0.92505258],
        [0.57133114, 0.24942302, 0.48371198, 0.93649213, 0.06559413],
        [0.29230551, 0.02015594, 0.11161171, 0.8038262 , 0.7533139 ]],

       [[0.71030602, 0.75958571, 0.46214534, 0.67682797, 0.95620418],
        [0.29000913, 0.19852795, 0.04688894, 0.40202996, 0.40702669],
        [0.91918977, 0.40004272, 0.29331841, 0.52401499, 0.36936105],
        [0.53993757, 0.23742997, 0.14061324, 0.39994457, 0.5333171 ]]])

array([[0.24800023, 0.33695557, 0.03353062, 0.58066617, 0.56607221],
       [0.17514119, 0.98660121, 0.4662178 , 0.81134032, 0.22050955],
       [0.71610125, 0.56825938, 0.51970461, 0.13970381, 0.29865019],
       [0.84912277, 0.42845382, 0.22731047, 0.23505944, 0.0809489 ]])

0.46621779851132317

array([[0.2518992 , 0.32564831, 0.02008145, 0.23930571, 0.78363088],
       [0.32248647, 0.74212245, 0.43295834, 0.43518467, 0.92505258],
       [0.57133114, 0.24942302, 0.48371198, 0.93649213, 0.06559413],
       [0.29230551, 0.02015594, 0.11161171, 0.8038262 , 0.7533139 ]])

0.43295833521312566

array([[0.71030602, 0.75958571, 0.46214534, 0.67682797, 0.95620418],
       [0.29000913, 0.19852795, 0.04688894, 0.40202996, 0.40702669],
       [0.91918977, 0.40004272, 0.29331841, 0.52401499, 0.36936105],
       [0.53993757, 0.23742997, 0.14061324, 0.39994457, 0.5333171 ]])

0.04688894167780444

In [11]:
# Unequal slicing, like for Cross-Validating using k-Fold.
# What I need is to:
#
# Full dataset:
# |--------------------------|
# |--------------------------|
#
#   1-Fold:
#   |---|---------------------|
#   |---|---------------------|
#
#   ...
#
#   k-Fold:
#   |---------------------|---|
#   |---------------------|---|
arr = np.arange(0, 500000).reshape((50000, 10))

chunks = 5
for k in range(chunks):
    chunk_size = int(arr.shape[0] / chunks) # Move out of loop to avoid extra computation.
    indices = range(k * chunk_size, (k + 1) * chunk_size)
    fold = arr[indices]
    rest = np.delete(arr, indices, 0)
    
    fold.shape
    rest.shape
    
    print('======')

(10000, 10)

(40000, 10)

(10000, 10)

(40000, 10)

(10000, 10)

(40000, 10)

(10000, 10)

(40000, 10)

(10000, 10)

(40000, 10)

## Fancy Indexing

In [16]:
arr = np.arange(0, 27).reshape((3, 3, 3))
# arr

# REMEMBER: 3D array = Depth, Rows, Columns
arr[0, 1, 1] = np.arange(0, 1) # We are passing a sequence to replace certain elements at certain
arr                            # indexes. BUT they need to match: HOW MANY ELEMENTS TO SEQUENCE!!

array([[[ 0,  1,  2],
        [ 3,  0,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [23]:
A = np.arange(10).reshape((2, 5))
B = np.arange(10, 20).reshape((2, 5))
C = np.zeros(10).reshape((2, 5))

A[np.arange(A.shape[0]), np.array([4, 4])] = C[np.arange(A.shape[0]), np.array([4, 4])] == 0

A
B
C

array([[0, 1, 2, 3, 1],
       [5, 6, 7, 8, 1]])

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Operations

In [19]:
arr = np.arange(0, 9).reshape((3, 3))
arr

arr / 9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0.        , 0.11111111, 0.22222222],
       [0.33333333, 0.44444444, 0.55555556],
       [0.66666667, 0.77777778, 0.88888889]])

In [23]:
# Functions:
arr = np.arange(0, 9).reshape((3, 3))
arr

## Mean:
np.mean(arr, axis=1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([1., 4., 7.])

## Casting

In [ ]:
# Pass a Python list as an argument to np.mean.
# If axis=None it will compute the mean as a flattened array, if axis=0 it will compute the mean
# along the row axis and so on.
np.mean([1, 2, 3, 4, 5, 6], axis=None)

(np.ones((10, 4)) == np.arange(4)).shape